[package]
name = "sparkrs"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
serenity = "0.12"
strum = { version = "0.26", features = ["derive"] }
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "1", features = ["full"] }
