[package]
name = "sparkrs"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
poise = "0.6.1"
redis = "0.28.2"
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "sqlite"] }
tokio = { version = "1", features = ["full"] }
